### ISSUE TITLE
ImportError: No module named kivy3.cameras

### ISSUE THREAD

**Issue by MartinBlondin** [nskrypnik/kivy3#5]
Hey i just installed your library with python 3.5 and i get this error:

```
[martin@hodeb examples]$ python3 example1.py 
[INFO   ] [Logger      ] Record log in /home/martin/.kivy/logs/kivy_16-11-19_8.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.2 (default, Nov  7 2016, 11:31:36) 
[GCC 6.2.1 20160830]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "example1.py", line 31, in <module>
     import kivy3
   File "/usr/lib/python3.5/site-packages/Kivy3-0.1-py3.5.egg/kivy3/__init__.py", line 5, in <module>
     from .cameras import PerspectiveCamera, OrthographicCamera
 ImportError: No module named 'kivy3.cameras'
```

it has something to do with this commit:
https://github.com/nskrypnik/kivy3/commit/166c922d5aab59b509e0b3b50551ddac5a42c95a

However another error occurs when i try an older version.
Then kivy gets a bit further but eventually spits out this:
```
[martin@hodeb examples]$ python3 example1.py 
[INFO   ] [Logger      ] Record log in /home/martin/.kivy/logs/kivy_16-11-19_11.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.2 (default, Nov  7 2016, 11:31:36) 
[GCC 6.2.1 20160830]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 375.20'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 660/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Shader      ] Read </home/martin/python/libraries/kivy3/examples/./simple.glsl>
 Traceback (most recent call last):
   File "example1.py", line 71, in <module>
     MainApp().run()
   File "/usr/lib/python3.5/site-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "example1.py", line 53, in build
     obj = loader.load(obj_path)
   File "/usr/lib/python3.5/site-packages/Kivy3-0.1-py3.5.egg/kivy3/loaders/objloader.py", line 205, in load
     return super(OBJLoader, self).load(source, **kw)
   File "/usr/lib/python3.5/site-packages/Kivy3-0.1-py3.5.egg/kivy3/loaders/loader.py", line 71, in load
     return self.parse()
   File "/usr/lib/python3.5/site-packages/Kivy3-0.1-py3.5.egg/kivy3/loaders/objloader.py", line 212, in parse
     obj.add(wvobj.convert_to_mesh())
   File "/usr/lib/python3.5/site-packages/Kivy3-0.1-py3.5.egg/kivy3/loaders/objloader.py", line 62, in convert_to_mesh
     material = Material()
   File "/usr/lib/python3.5/site-packages/Kivy3-0.1-py3.5.egg/kivy3/materials.py", line 52, in __init__
     for k, v in kw.iteritems():
 AttributeError: 'dict' object has no attribute 'iteritems'
```
Do you know what could be causing this? Im not that used to kivy yet so i cant really read your code.

**Comment by KeyWeeUsr** [comment]
I couldn't get the `ImportError`, but the second one it py3 related:

    AttributeError: 'dict' object has no attribute 'iteritems'

[This](https://docs.python.org/3/library/2to3.html#2to3fixer-dict) happened. The repo is probably py2, but it should be easy to fix with `kw.items()` on that line.

**Comment by nskrypnik** [comment]
As KeyWeeUsr mentioned above the repository is really for python 2, so that's why you get an error with py3. Haven't been working with Python for almost two years so don't really now how to maintain repos for both py2 and py3.

Anyway abt that cameras issue - it has been resolved. Try to pull.
